### ISSUE TITLE
GyazoのHTTPS化への対応

### ISSUE THREAD

**Issue by na2hiro** [uhyo/socketchat#65]

**Comment by Tatamo** [comment]
Gyazoの現状の仕様について。
現在のGyazoは以下のURLのようにHTTPS化されています。
https://gyazo.com/388b582ad1e9f9faf188465f31f96d06

以下のように/rawを取得することで画像そのものを取得でき、
https://gyazo.com/388b582ad1e9f9faf188465f31f96d06/raw
この画像では
https://i.gyazo.com/388b582ad1e9f9faf188465f31f96d06.png
にリダイレクトされます。

画像ファイルそのものは、基本的にはpngで保持され、画像のサイズが一定より大きい場合はjpg形式となります。
また、画像の直接アップロードによってgifファイルもアップロードされる可能性があります。

なお、動画の場合は/rawで取得できるのはアニメgifとなります。
https://gyazo.com/8379d8c5d20174c7786d5fcf5d7b31ae について、
https://gyazo.com/8379d8c5d20174c7786d5fcf5d7b31ae/raw にアクセスすると
https://i.gyazo.com/8379d8c5d20174c7786d5fcf5d7b31ae.gif が得られる。
https://i.gyazo.com/8379d8c5d20174c7786d5fcf5d7b31ae.mp4 にmp4形式のファイルが配置されている。

**Comment by na2hiro** [comment]
詳しい情報ありがとうございます．
rawのURLならimgタグに埋め込めるので，一律そちらを採用しようと思います．
